### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by rheineke**
I made changes in several ways to get this running on Mac OS X with Python3:
- Added Python3 support
- Kept Python2 support through [future](https://pypi.python.org/pypi/future) package
- Switched to [wxPython Phoenix](http://wxpython.org/Phoenix/docs/html/main.html) for gxstools. There is no point release yet, but wxPython doesn't support Python3 as far as I know.
- Cleaned up the imports
- Added a few unittests
- Added all package dependencies to pip file. The versions are strict and can almost certainly be relaxed.
- Some code refactoring and reformatting

Not tested on Linux or Windows, but gxstools works on Python2 for me.

### CODE REVIEW

**Comment by xesscorp** [comment]
Thanks for all the work, Reece! 

As you said, you used a point release of wxpython phoenix in order to use python 3. Currently, the standard 2.9 release of wxpython is giving potential users enough problems with installation. I'm not sure how easy it will be for them to use the phoenix version. Do you think xstools should move to another GUI library such as Tcl/Tk, Qt or (insert name here)? (Tcl/Tk comes bundled with python and I've used it for another tool, but maybe there's something better...) All the wx stuff is in the gxstools.py file. I could probably do that if I knew which library would be the best replacement.

**Comment by rheineke** [comment]
Sounds like there are a couple of related issues.

I didn't have any problems with wxpython by installing via pip. I believe the Windows and OS X versions bundle everything needed. Pip install instructions in the readme could help here.

I considered porting gxstools.py to Tcl/Tk, but it's not an obvious win over wxpython. It requires installing tcl on OS X and Linux afaik, though apt-get makes that easy enough on Linux. Anyways, wxpython phoenix looks like it's under active development and there might be a point release soon.

What platforms do you want to target with xstools? Windows and Linux are the obvious choices since Vivado runs on these, but OS X support is very convenient for myself. Intel only or ARM too? Choosing platforms might make the GUI choice easier.

**Comment by xesscorp** [comment]
Hi, Reece. I pulled all your changes into a branch called python3. Then I made a few small changes to convert the device type info from the bitstream into strings. I saw you already encountered that problem.) Now the board test diagnostic works for both the XuLA and XuLA2 boards.

Here are a few bugs I'm working to fix in gxstools.py:
- Drag-and-drop doesn't work for downloading SDRAM files or bitstream files.
- Downloading to the SDRAM doesn't work (it finishes too quickly and nothing gets downloaded).
- Downloading to the FPGA doesn't work (the download arrow never gets activated).

I'm sure some (maybe all) of these are just things I need to adjust for the wxPython Phoenix module. Let me know if you've seen any of these problems. If not, these may be Windows-specific.

Thanks for letting me know about Phoenix. Unlike the standard wxpython, I was able to install it using pip. That's going to be a big help.

**Comment by rheineke** [comment]
Dave, thanks for pulling in my changes.
- The drag-and-drop doesn't work because I commented out lines 200-202 in gxstools.py. Phoenix's API must have changed, and I haven't found the correct calls yet.
- I never tested the SDRAM functionality now that you mention it. What bitstream, if any, should I use from the xula2 folder and what should the upper and lower addresses be set to?
- I _think_ the FPGA page works for me. When I mouse over the download arrow, it becomes highlighted and my XuLA LED blinks after pressing with an eventual success dialog. Do you mean something else by activate?
  screen shot 2016-06-19 at 9 25 22 pm

I tried to install Phoenix from source on a Linux box, and I have not yet succeeded. I also learned that OS X does, in fact, come with a slightly older version of Tcl/Tk installed. Tkinter is probably a better choice in the long run, but for now it'll be much easier to just get Phoenix working.

**Comment by rheineke** [comment]
I found another bug on the flash download. Looks like a str/bytes issue with Python 3. Should I create an issue to track these? I'll have a fix regardless.

**Comment by xesscorp** [comment]
Reece, apologies for the late reply. You can create an issue if you want, but you can also do a pull request with the commit message explaining what you're fixing. Whatever is easiest/most sensible to you is fine by me. Thanks for the help.

**Comment by rheineke** [comment]
I have the flash download working on Python 3 and OS X. It should be working on Python 2 except an error is thrown in IntelHex on my setup. I added a few unit tests including one that replicates this error for me with minimal code: test_xsbitarray.test_to_intel_hex.

**Comment by parasyte** [comment]
FWIW, I've used `tkiner` with very simple GUI projects in the past, and it does really well if you're not doing anything ✨ fancy ✨. (Aside: one of my projects got derailed by custom theming, so I switched the GUI over to HTML+CSS.)

But if you're not doing things that require ridiculous GUI components, `tkinter` is fantastic; it's fully supported cross-platform, and it's usable with Python 2+ out of the box. (Linux builds of Python for popular distros include tcl/tk as well.) It's absolutely a great benefit.

The downside is that GUIs written with `tkinter` do not have that native platform "look and feel" ... Which is why I was so interested in adding theming.

In any case, I'm thankful to have found this PR; I'm considering buying a XuLA2 (looks like an awesome board, BTW!) and being an OS X user myself, having the ability to use my daily driver is a very big selling point. :+1:

**Comment by rheineke** [comment]
@parasyte I started [a branch to build a `tkinter` GUI](https://github.com/rheineke/XSTOOLs/tree/tk) around the same time as this branch.

**Comment by rheineke** [comment]
@xesscorp What can I do to move this pull request and project along? It'd be great to merge in the changes that @hstarmans and I have done.

**Comment by xesscorp** [comment]
I'll try to get some movement on this on Saturday.

**Pull request merged**
